<?php

// Replacing factoid boxes in old articles

function factoid_function( $atts, $content = null ) {
$content = str_replace('<p', '<p class="vf-box__text"', $content);
$content = str_replace('<h2', '<h2 class="vf-box__heading"', $content);
    return '<div class="vf-box vf-box--normal vf-box-theme--primary">' .  $content . '</div>';
}

add_shortcode('fact-box', 'factoid_function');

// removes empty <p> in factoid box

add_filter('the_content', 'remove_empty_p', 20, 1);
function remove_empty_p($content){
    $content = force_balance_tags($content);
    return preg_replace('#<p>\s*+(<br\s*/*>)?\s*</p>#i', '', $content);
}

// Expose user email id in user api
// https://gitlab.ebi.ac.uk/emblorg/backlog/-/issues/585
register_rest_field( 'user', 'user_email',
    array(
        'get_callback'    => function ( $user ) {
            //return $user['email'];
         return get_userdata($user['id'])->user_email;
        },
        'update_callback' => null,
        'schema'          => null,
    )
);


// CHILD THEME CSS FILE

add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
	
	$parent_style = 'parent-style'; 
	
    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
	get_stylesheet_directory_uri() . '/style.css',
	array( $parent_style ),
	wp_get_theme()->get('Version')
);
}

/**
 * Load ACF JSON from theme
 */
add_filter(
	'acf/settings/load_json',
	'vf_wp_news__acf_settings_load_json',
	1
  );

function vf_wp_news__acf_settings_load_json($paths) {
    $paths[] = get_stylesheet_directory() . '/acf-json';
    return $paths;
  }



// POST THUMBNAILS
// 
add_theme_support( 'post-thumbnails' );
add_theme_support( 'title-tag' );

// REMOVES CUSTOM IMAGE SIZES

function remove_extra_image_sizes() {
	foreach ( get_intermediate_image_sizes() as $size ) {
		if ( !in_array( $size, array( 'thumbnail', 'medium', 'medium_large', 'large' ) ) ) {
			remove_image_size( $size );
		}
	}
}
 
add_action('init', 'remove_extra_image_sizes');


//Adding vf-list__item class to a list generated by Wordpress

add_filter('wp_list_categories', 'add_vf_class_wp_list_categories');
function add_vf_class_wp_list_categories($list) {

    $cats = get_categories('hide_empty=0');
    foreach($cats as $cat) {
        $find = 'cat-item-' . $cat->term_id . '"';
        $replace = 'vf-list__item' . '"';
        $list = str_replace( $find, $replace, $list );
        $find = 'cat-item';
        $replace = 'vf-list__item' . '"';
        $list = str_replace( $find, $replace, $list );
    }

    return $list;
}

add_filter('wp_list_categories', 'addClassToLinks');
function addClassToLinks($content){
	$class_to_add = 'vf-list__link';

    return str_replace( '<a href="',  '<a class="'. $class_to_add. '" href="', $content);
}


// POPULAR POSTS 

function popular_posts($post_id) {
	$count_key = 'popular_posts';
	$count = get_post_meta($post_id, $count_key, true);
	if ($count == '') {
		$count = 0;
		delete_post_meta($post_id, $count_key);
		add_post_meta($post_id, $count_key, '0');
	} else {
		$count++;
		update_post_meta($post_id, $count_key, $count);
	}
}

function track_posts($post_id) {
	if (!is_single()) return;
	if (empty($post_id)) {
		global $post;
		$post_id = $post->ID;
	}
	popular_posts($post_id);
}
add_action('wp_head', 'track_posts');



//ADDING CLASS TO A LINK IN CATEGORY
//
function replace_category_class( $thelist, $separator, $parents){
    $class_to_add = 'vf-link';
    return str_replace('<a href="',  '<a class="'. $class_to_add. '" href="', $thelist);
}

add_filter('the_category', __NAMESPACE__ . '\\replace_category_class',10,3);


 // MAGAZINE COVER WIDGET 1
function mag1_widgets_init() {

	register_sidebar( array(
		'name'          => 'Magazine cover right',
		'id'            => 'magazine_cover_1',
		'before_widget' => '<div>',
		'after_widget'  => '</div>',
		'before_title'  => '<h2>',
		'after_title'   => '</h2>',
	) );

}
add_action( 'widgets_init', 'mag1_widgets_init' );

// MAGAZINE COVER WIDGET 2
function mag2_widgets_init() {

	register_sidebar( array(
		'name'          => 'Magazine cover left',
		'id'            => 'magazine_cover_2',
		'before_widget' => '<div>',
		'after_widget'  => '</div>',
		'before_title'  => '<h2>',
		'after_title'   => '</h2>',
	) );

}
add_action( 'widgets_init', 'mag2_widgets_init' );

 // TOPICS WIDGET 1
 function top1_widgets_init() {

	register_sidebar( array(
		'name'          => 'Topics left',
		'id'            => 'topics_left',
		'before_widget' => '<div>',
		'after_widget'  => '</div>',
		'before_title'  => '',
		'after_title'   => '',
	) );

}
add_action( 'widgets_init', 'top1_widgets_init' );

 // TOPICS WIDGET 2
 function top2_widgets_init() {

	register_sidebar( array(
		'name'          => 'Topics right',
		'id'            => 'topics_right',
		'before_widget' => '<div>',
		'after_widget'  => '</div>',
		'before_title'  => '',
		'after_title'   => '',
	) );

}
add_action( 'widgets_init', 'top2_widgets_init' );

// REMOVE LIST FROM CATEGORY

foreach((get_the_category()) as $category) { 
    echo $category->category_nicename . ' '; 
    echo get_category_link($category->cat_ID);;
} 

// DISPLAY CUSTOM FIELDS IN THE MENU

add_filter('acf/settings/remove_wp_meta_box', '__return_false');

add_filter('acf/settings/show_admin', '__return_true');
function my_acf_save_post( $post_id ) {
    // get new value
    $user = get_field( 'author', $post_id );
	if( $user ) {
		wp_update_post( array( 'ID'=>$post_id, 'post_author'=>$user['ID']) ); 
	}
}
add_action('acf/save_post', 'my_acf_save_post', 20);

// ARCHIVES PAGE
add_action( 'init', 'create_post_type' );
function create_post_type() {
    register_post_type( 'archives',
        array(
            'labels' => array(
                'name' => __( 'archives' ),
                'singular_name' => __( 'archives' )
            ),
        'public' => true,
        'has_archive' => true,
        )
    );
}
// CUSTOM ACF COLOR PICKER SWATCHES

function my_acf_collor_pallete_script() {
    ?>
    <script type="text/javascript">
    (function($){
        
        acf.add_filter('color_picker_args', function( args, $field ){

            args.palettes = ['#007B53', '#54585A','#A6093D','#193F90','#563D82','#B65417']
            
            console.log(args);

            return args;
        });
        
    })(jQuery);
    </script>
    <?php
}

add_action('acf/input/admin_footer', 'my_acf_collor_pallete_script');

function my_acf_collor_pallete_css() {
    ?>
    <style>
		
		
        .acf-color_picker .iris-picker .iris-border {
            width: 200px !important;
            height: 10px !important;
        }
        .acf-color_picker .wp-picker-input-wrap,
        .acf-color_picker .iris-picker .iris-slider,
        .acf-color_picker .iris-picker .iris-square {
            display:none !important;
        }
    </style>
    <?php
}

add_action('acf/input/admin_head', 'my_acf_collor_pallete_css');

// Remove Yoast SEO Prev/Next URL from all pages

add_filter( 'wpseo_next_rel_link', '__return_false' );
add_filter( 'wpseo_prev_rel_link', '__return_false' );

// Prepends WordPress RSS feed content with the featured image

add_filter('the_content', 'featured_image_in_rss_feed');
function featured_image_in_rss_feed( $content ) {
 global $post;
 if( is_feed() ) {
 if ( has_post_thumbnail( $post->ID ) ){
 $prepend = '<div>' . get_the_post_thumbnail( $post->ID, 'medium', array( 'style' => 'margin-bottom: 10px;' ) ) . '</div>';
 $content = $prepend . $content;
 }
 }
 return $content;
}

  /**
   * Add metadata to REST API
   */

  function register_display_api_field()
{
    register_rest_field('post', 'field_target_display',
        array(
            'get_callback' => 'get_display_api_field',
            'schema' => null,
        )
    );
}

add_action('rest_api_init', 'register_display_api_field');

function get_display_api_field($post)
{
    return get_field('field_target_display', $post['id']);
}

// Add featured image to REST API
add_action('rest_api_init', 'register_rest_images' );
function register_rest_images(){
    register_rest_field( array('post'),
        'fimg_url',
        array(
            'get_callback'    => 'get_rest_featured_image',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}
function get_rest_featured_image( $object, $field_name, $request ) {
    if( $object['featured_media'] ){
        $img = wp_get_attachment_image_src( $object['featured_media'], 'app-thumb' );
        return $img[0];
    }
    return false;
}

// Allows to prioritse ACF image field over a Gravatar profile

add_filter('get_avatar', 'custom_profile_avatar', 10, 5);
function custom_profile_avatar( $avatar, $id_or_email, $size, $default, $alt ) {

    $user = '';
    
    // Get user by id or email
    if ( is_numeric( $id_or_email ) ) {
        $id   = (int) $id_or_email;
        $user = get_user_by( 'id' , $id );

    } elseif ( is_object( $id_or_email ) ) {
        if ( ! empty( $id_or_email->user_id ) ) {
            $id   = (int) $id_or_email->user_id;
            $user = get_user_by( 'id' , $id );
        }
    } else {
        $user = get_user_by( 'email', $id_or_email );
    }
    if ( ! $user ) {
        return $avatar;
    }

    // Get the user id
    $user_id = $user->ID;

    // Get the file id
    $image_id = get_user_meta($user_id, 'vf_wp_avatar_image', true); // CHANGE TO YOUR FIELD NAME

    // Bail if we don't have a local avatar
    if ( ! $image_id ) {
        return $avatar;
    }

    // Get the file size
    $image_url  = wp_get_attachment_image_src( $image_id, 'thumbnail' ); // Set image size by name
    // Get the file url
    $avatar_url = $image_url[0];
    // Get the img markup
    $avatar = '<img alt="' . $alt . '" src="' . $avatar_url . '" class="vf-author--avatar' . '" height="' . $size . '" width="' . $size . '"/>';
    // Return our new avatar
    return $avatar;
}


/// YOAST SEO overwrite canonical url for EBI news

function ebi_news_canonical_url( $canonical ) {
    global $post;
    $display = get_field('field_target_display', $post->ID);
    $category = get_the_category($post->ID);
    $cat_slug = strtolower($category[0]->cat_name);
    if ( (is_single()) && ($display == 'embl-ebi') ) {
      $canonical = 'https://www.ebi.ac.uk/about/news/'. $cat_slug . '/' . $post->post_name;
    }
  
    return $canonical;
  }
  
  add_filter( 'wpseo_canonical', 'ebi_news_canonical_url', 20 );

  
  function ebi_news_opengraph_url( $url ) {
      global $post;
      $display = get_field('field_target_display', $post->ID);
      $category = get_the_category($post->ID);
      $cat_slug = strtolower($category[0]->cat_name);
      if ( (is_single()) && ($display == 'embl-ebi') ) {
          $url = 'https://www.ebi.ac.uk/about/news/'. $cat_slug . '/' . $post->post_name;
        }
        
        return $url;
  }

    add_filter( 'wpseo_opengraph_url', 'ebi_news_opengraph_url' );
  
?>
